server:
  http_listen_port: {{ stats_loki_http_port }}
  log_level: {{ stats_loki_log_level }}

memberlist:
  join_members:
    - localhost

schema_config:
  configs:
    - from: 2021-08-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  aws:
    s3: s3://{{ minio_admin_username }}:{{ minio_admin_password }}@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ minio_api_port }}/loki-data
    s3forcepathstyle: true
    insecure: true

ruler:
  storage:
    s3:
      bucketnames: loki-ruler

limits_config:
  retention_period: {{ stats_loki_log_retention }}
  allow_structured_metadata: true

table_manager:
  retention_deletes_enabled: true
  retention_period: {{ stats_loki_log_retention }}
