repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.14.6
    hooks:
      - id: ansible-lint
        args: ["--skip-list", "fqcn-builtins"]
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.30.0
    hooks:
      - id: yamllint

#   - repo: https://github.com/igorshubovych/markdownlint-cli
#     rev: v0.32.2
#     hooks:
#       - id: markdownlint
