---
ansible_nas_hostname: ansible-nas
keep_packages_updated: false

ansible_nas_extra_packages:
    - smartmontools
    - htop
    - zfsutils-linux
    - bonnie++
    - unzip
    - lm-sensors

ansible_nas_additional_tasks:
    - name: Install ctop via apt
      ansible.builtin.apt:
          name: ctop
          state: present
      when: ansible_distribution_version is version('24.04', '<')

    - name: Install ctop from GitHub
      ansible.builtin.get_url:
          url: https://github.com/bcicen/ctop/releases/latest/download/ctop-linux-amd64
          dest: /usr/local/bin/ctop
          mode: '0755'
          force: true
      when: ansible_distribution_version is version('24.04', '>=')

ansible_nas_timezone: Etc/UTC
