---
# ---------------------------------------------------------------------------- #
#                                    Traefik                                   #
# ---------------------------------------------------------------------------- #
traefik_cftunnel_enabled: false
traefik_cftunnel_available_externally: false

# Directories
traefik_cftunnel_data_directory: "{{ docker_home }}/traefik_cftunnel"

# Network
traefik_cftunnel_port_http: "80"
traefik_cftunnel_port_https: "443"
traefik_cftunnel_port_ui: "8083"

traefik_cftunnel_hostname: "traefik_cftunnel"
traefik_cftunnel_image_name: "traefik"
traefik_cftunnel_image_version: "latest"
traefik_cftunnel_log_level: "INFO"


# find the relevant name and environment variables for your DNS provider at https://go-acme.github.io/lego/dns/.
# More info at https://doc.traefik.io/traefik/https/acme/
traefik_cftunnel_dns_provider: cloudflare 
traefik_cftunnel_environment_variables: #!
  CF_DNS_API_TOKEN: "abcdabcd123412341234"

# Ansible-NAS requests a wildcard certificate for your domain, so there should be no reason to have to use the staging
# letsencrypt acme server. If you do want to flip between staging/production, you might need to stop Traefik and clear
# the "{{ docker_home }}/traefik" after changing this setting.
# traefik_acme_server: "https://acme-staging-v02.api.letsencrypt.org/directory" # staging
traefik_cftunnel_acme_server: "https://acme-v02.api.letsencrypt.org/directory" # production

# specs
traefik_cftunnel_memory: 1g

# Docker
traefik_cftunnel_container_name: "traefik_cftunnel"

# ---------------------------------------------------------------------------- #
#                                  cloudflared                                 #
# ---------------------------------------------------------------------------- #
traefik_cftunnel_cloudflared_enabled: false
# traefik_cftunnel_cloudflared_available_externally: false

# directories
traefik_cftunnel_cloudflared_data_directory: "{{ docker_home }}/cloudflared"

# network
# traefik_cftunnel_cloudflared_port: "9999"
traefik_cftunnel_cloudflared_hostname: "cloudflared"

# specs
traefik_cftunnel_cloudflared_memory: 1g

# docker
traefik_cftunnel_cloudflared_container_name: cloudflared

traefik_cftunnel_cloudflared_tunnel_token: 111222223333