# stats_enabled: false
stats_loki_enabled: false
stats_loki_available_externally: false
stats_internet_speed_test_enabled: false
stats_prometheus_available_externally: false
promtail_enabled: false
promtail_available_externally: false
stats_grafana_available_externally: false
# directories
stats_loki_data_directory: "{{ docker_home }}/loki"
stats_telegraf_config_directory: "{{ docker_home }}/stats/telegraf/config"
stats_prometheus_data_directory: "{{ docker_home }}/stats/prometheus/data"
stats_prometheus_config_directory: "{{ docker_home }}/stats/prometheus/config"
promtail_data_directory: "{{ docker_home }}/promtail"
stats_grafana_data_directory: "{{ docker_home }}/stats/grafana/data"
stats_grafana_config_directory: "{{ docker_home }}/stats/grafana/config"
# network
stats_loki_hostname: "loki"
stats_loki_network_name: "loki"
stats_loki_http_port: "3100"
stats_prometheus_port: "9090"
stats_telegraf_port: "9273"
stats_telegraf_influxdb_port: "8086"
stats_prometheus_smartctl_port: "9902"
stats_speedtest_exporter_port: "9798"
stats_hddtemp_port: "7634"
stats_prometheus_hostname: "prometheus"
promtail_hostname: "promtail"
promtail_network_name: "promtail"
promtail_port: "9080"
stats_grafana_port: "3000"
stats_grafana_hostname: "grafana"
# docker:
stats_grafana_container_name: "stats-grafana"
stats_grafana_image_name: "grafana/grafana"
stats_grafana_image_version: "latest"
stats_loki_container_name: "loki"
stats_loki_image_name: "grafana/loki"
stats_loki_image_version: "latest"
stats_prometheus_container_name: "stats-prometheus"
stats_prometheus_image_name: "prom/prometheus"
stats_prometheus_image_version: "latest"
promtail_container_name: "promtail"
promtail_image_name: "grafana/promtail"
promtail_image_version: "latest"
stats_telegraf_container_name: "stats-telegraf"
stats_telegraf_image_name: "telegraf"
stats_telegraf_image_version: "latest"
stats_smartctl_container_name: "stats-smartctl"
stats_smartctl_docker_image_name: "matusnovak/prometheus-smartctl"
stats_smartctl_docker_image_version: "latest"
stats_speedtest_container_name: "stats-speedtest"
stats_speedtest_docker_image_name: "miguelndecarvalho/speedtest-exporter"
stats_speedtest_docker_image_version: "latest"
stats_hddtemp_docker_container_name: "stats-hddtemp"
stats_hddtemp_docker_image_name: "modem7/hddtemp-docker"
stats_hddtemp_docker_image_tag: "latest"
# specs
stats_loki_memory: "1g"
stats_telegraf_memory: 1g
stats_prometheus_memory: 1g
stats_prometheus_smartctl_memory: 1g
promtail_memory: "1g"
stats_hddtemp_memory: 128m
stats_speedtest_exporter_memory: 256m
stats_grafana_memory: 1g
# config
stats_loki_log_retention: 672h
stats_loki_log_level: warn
stats_prometheus_retention_time: 365d
stats_prometheus_retention_size: 30GB
promtail_loki_url: http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ stats_loki_http_port }}/loki/api/v1/push
stats_collection_interval: 15s
stats_speedtest_collection_interval: 1h

# uncomment to scrape more hosts
# stats_prometheus_additional_hosts:
#  - 192.168.1.1:9100

# uncomment to scrape metrics from HomeAssistant. You'll need to create a long lived access token.
# stats_hass_long_lived_access_token: addfasdfasdf
