---
- name: Restart Grafana
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    restart: true
  listen: "restart grafana"

- name: Restart Promtail
  community.docker.docker_container:
    name: "{{ stats_promtail_container_name }}"
    state: started
    restart: yes
